In [1]:
import cv2
import numpy as np
import os

# Set the path to the test image directory
test_dir = "D:/FYP/Dataset/Dataset for Camera Settings/Test Data"

# Set the desired image size
img_size = (512, 512)

# Create an empty list to store the preprocessed test images
test_images = []

# Loop over the files in the test directory and preprocess each image
for filename in os.listdir(test_dir):
    if filename.lower().endswith(".jpg"):

        # Load the image
        img = cv2.imread(os.path.join(test_dir, filename))
        # Resize the image to the desired size
        img = cv2.resize(img, img_size)
        # Convert the image to a numpy array and normalize the pixel values
        img = np.asarray(img, dtype="float32") / 255.0
        # Append the preprocessed image to the list of test images
        test_images.append(img)

# Convert the list of test images to a numpy array
test_images = np.array(test_images)

# Print the shape of the test images array to make sure it matches the expected shape
print(test_images.shape)


(60, 512, 512, 3)


In [2]:
from sklearn.metrics import confusion_matrix, classification_report
from keras.models import Model, load_model
import numpy as np


# Load the saved ResNet50 model
# resnet50 = load_model("D:/FYP/Phaedra_BE/resnet50.h5")
# resnet50 = load_model("D:/FYP/Dataset/Dataset for Camera Settings/resnet50.h5")
resnet50 = load_model("D:/FYP/Phaedra_BE/resnet502.h5")


# Assign the possible classes
cm_classes = ['c - ISO Low', '1 - Correct', 'b - Shutter Speed Low', 'd - ISO High', 'a - Shutter Speed High']


# Use the model to predict class labels for the test data
y_pred = resnet50.predict(test_images)

# Define the true labels for the test data
# y_true = np.array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0])

n_samples = 60
n_classes = 5
y_true = np.array([i % n_classes for i in range(n_samples)])


assert len(test_images) == len(y_true), "Number of test images does not match the length of y_true"

# Convert the predicted probabilities into class labels (i.e., the index of the highest probability)
y_pred_labels = np.argmax(y_pred, axis=1)

# Calculate the confusion matrix
cm = confusion_matrix(y_true, y_pred_labels)

# Calculate the classification report (which includes precision, recall, and F1 score)
report = classification_report(y_true, y_pred_labels, target_names=cm_classes)

# Print the confusion matrix and classification report
print("Confusion Matrix:")
print(cm)
print("Classification Report:")
print(report)

2/2 [==============================] - 17s 8s/step
Confusion Matrix:
[[ 0  0  0  0 12]
 [ 0  0  0  0 12]
 [ 0  0  0  0 12]
 [ 0  0  0  0 12]
 [ 0  0  0  0 12]]
Classification Report:
                        precision    recall  f1-score   support

           c - ISO Low       0.00      0.00      0.00        12
           1 - Correct       0.00      0.00      0.00        12
 b - Shutter Speed Low       0.00      0.00      0.00        12
          d - ISO High       0.00      0.00      0.00        12
a - Shutter Speed High       0.20      1.00      0.33        12

              accuracy                           0.20        60
             macro avg       0.04      0.20      0.07        60
          weighted avg       0.04      0.20      0.07        60



c:\Users\Ph03nix6\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Ph03nix6\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Ph03nix6\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(av